
@startuml

' 页面
class 登录

class 審査ページ{
    显示所有待审核的资格信息;
    允许管理员对资格信息进行审批和拒绝;
    提供搜索和过滤功能;
}

class アップデートページ{
    允许用户上传个人资格信息;
    提供表单用于上传信息;
}
class 資格種類の閲覧ページ{
    列出所有可用的资格种类;
    显示每种资格的详细信息;
    提供搜索和过滤功能;
}


class 資格保有者の検索ページ{
    允许管理层按照各种条件搜索已经拥有某种特定资格的员工;
    显示搜索结果;
    提供搜索和过滤功能;
}
class 部下の資格保有の閲覧ページ{
    允许管理层查看自己所管理的所有员工的资格信息;
    显示每个员工的资格信息;
    提供搜索和过滤功能;
}

' 一般社员功能
class 一般社員 {
    アップデートページ
    資格種類の閲覧ページ
}


' 管理层功能
class 管理层 {
    資格保有者の検索ページ
    部下の資格保有の閲覧ページ
}


' 依存关系
登录 --> 一般社員
登录 --> 管理层
一般社員 --> 資格種類の閲覧ページ
一般社員 --> アップデートページ
管理层 --> 検索と統計ページ
管理层 --> 審査ページ
検索と統計ページ-->資格保有者の検索ページ
検索と統計ページ-->部下の資格保有の閲覧ページ
アップデートページ -.- 審査ページ : 提交资格信息
@enduml
