FROM python:3.9.3

# To SET DB initialize disable
# True/False
ENV COLPRO_TB_INIT_DB False

# backendセットアップ
ENV DEBIAN_FRONTEND noninteractive
ENV PROJECT_ROOTDIR /work/
WORKDIR $PROJECT_ROOTDIR
COPY requirements.txt $PROJECT_ROOTDIR

# モジュールのセットアップ
RUN pip install -U pip && \
    pip install -r requirements.txt

WORKDIR $PROJECT_ROOTDIR