@startuml

skinparam monochrome true

package "CMS" <<rectangle>> {
  package "Employee" <<rectangle>> {
    ' テーブル
    entity "userinfo" {
      + employee_id [PK] : integer
      ==
      name : character varying
      create_datetime : timestamp without time zone
      update_datetime : timestamp without time zone
    }
    entity "certificate_plan_event"{
      + certificate_plan_id [PK] : integer
      ==
      employee_id [FK] : integer
      name : character varying
      certificate_name_plan : character varying
      test_time : timestamp without time zone
      result_time : timestamp without time zone
      create_datetime : timestamp without time zone
      update_datetime : timestamp without time zone
    }
    entity "certificate_result" {
      + certificate_id [PK] : integer
      ==
      employee_id [FK] : integer
      name : character varying
      certificate_name : character varying
      certificate_result : boolean
      credentrials : character varying
      create_datetime : timestamp without time zone
      update_datetime : timestamp without time zone
    }
    entity "login" {
      + employee_id [PK] : integer
      ==
      mail : character varying
      password : character varying
      create_datetime : timestamp without time zone
      update_datetime : timestamp without time zone
    }
    entity "login_event" {
      + employee_id [PK] : integer
      + login_datetime [PK] : timestamp without time zone
      ==
      logout_datetime : timestamp without time zone
    }


    ' リレーション
    userinfo --|{ certificate_plan_event
    userinfo ||--|| login
    userinfo --|{ certificate_result
    login --|{ login_event

  }

  package "certificate_info" <<rectangle>>{
    ' テーブル
    entity "certificate_info" {
      + certificate_id [PK] : integer
      ==
      certificate_name : character varying
    }


  }


  ' リレーション
userinfo --|{ certificate_info

}
@enduml