openapi: 3.0.0
info:
  title: 在线员工证书登录系统 API
  version: 1.0.0
servers:
  - url: 'https://api.example.com/v1'
paths:
  /login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
                type:
                  type: string
                  enum: ['社員', '上司']
      responses:
        '201':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '500':
          description: 未知错误
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              