@startuml
!define Table(name,desc) class name as "desc" << (T,#FFAAAA) >>
!define primary_key(x) <b>x</b>
!define unique(x) <color:red>x</color>
!define not_null(x) <u>x</u>
!define foreign_key(x) <i>x</i>

Table(users, "用户表") {
    primary_key(id) : int <<generated>>
    not_null(username) : varchar
    not_null(password) : varchar
    not_null(email) : varchar
    not_null(type) : enum('社員', '上司')
}

Table(certificates, "证书表") {
    primary_key(id) : int <<generated>>
    not_null(userid) : varchar
    foreign_key(userid) -r-> users.id
    not_null(accesstime) : int
    not_null(file) : object
}

Table(messages, "消息表") {
    primary_key(id) : int <<generated>>
    not_null(userid) : varchar
    foreign_key(userid) -r-> users.id
    not_null(accesstime) : int
}

Table(cert_categories, "证书类别表") {
    primary_key(id) : int <<generated>>
    not_null(certCategory) : varchar
}

Table(cert_info, "证书信息表") {
    primary_key(id) : int <<generated>>
    not_null(cert_category_id) : int
    foreign_key(cert_category_id) -r-> cert_categories.id
    not_null(cert_name) : varchar
    not_null(description) : text
}

Table(cert_holder_search, "证书持有者搜索表") {
    primary_key(id) : int <<generated>>
    not_null(cert_id) : int
    foreign_key(cert_id) -r-> cert_info.id
    not_null(user_id) : int
    foreign_key(user_id) -r-> users.id
}

Table(subordinate_cert_view, "部下的证书查看表") {
    primary_key(id) : int <<generated>>
    not_null(cert_id) : int
    foreign_key(cert_id) -r-> cert_info.id
    not_null(user_id) : int
    foreign_key(user_id) -r-> users.id
    not_null(manager_id) : int
    foreign_key(manager_id) -r-> users.id
}

Table(cert_review, "证书审核表") {
    primary_key(id) : int <<generated>>
    not_null(cert_id) : int
    foreign_key(cert_id) -r-> certificates.id
    not_null(manager_id) : int
    foreign_key(manager_id) -r-> users.id
    not_null(status) : enum('待审核', '批准', '拒绝')
}

users --|> messages : 用户_消息
users --|> certificates : 用户_资格证书
cert_categories --|> certificates : 资格种类_资格证书

@enduml
